CREATE TABLE big_vector.us_blocks AS
SELECT  * 
FROM big_vector.alabama
UNION ALL
SELECT  * 
FROM big_vector.arizona
UNION ALL
SELECT  * 
FROM big_vector.arkansas
UNION ALL
SELECT  * 
FROM big_vector.california
UNION ALL
SELECT  * 
FROM big_vector.colorado
UNION ALL
SELECT  * 
FROM big_vector.connecticut
UNION ALL
SELECT  * 
FROM big_vector.dc
UNION ALL
SELECT  * 
FROM big_vector.delaware
UNION ALL
SELECT  * 
FROM big_vector.florida
UNION ALL
SELECT  * 
FROM big_vector.georgia
UNION ALL
SELECT  * 
FROM big_vector.hawaii
UNION ALL
SELECT  * 
FROM big_vector.idaho
UNION ALL
SELECT  * 
FROM big_vector.illinois
UNION ALL
SELECT  * 
FROM big_vector.indiana
UNION ALL
SELECT  * 
FROM big_vector.iowa
UNION ALL
SELECT  * 
FROM big_vector.kansas
UNION ALL
SELECT  * 
FROM big_vector.kentucky
UNION ALL
SELECT  * 
FROM big_vector.louisiana
UNION ALL
SELECT  * 
FROM big_vector.maine
UNION ALL
SELECT  * 
FROM big_vector.maryland
UNION ALL
SELECT  * 
FROM big_vector.massachusetts
UNION ALL
SELECT  * 
FROM big_vector.michigan
UNION ALL
SELECT  * 
FROM big_vector.minnesota
UNION ALL
SELECT  * 
FROM big_vector.mississippi
UNION ALL
SELECT  * 
FROM big_vector.missouri
UNION ALL
SELECT  * 
FROM big_vector.montana
UNION ALL
SELECT  * 
FROM big_vector.nebraska
UNION ALL
SELECT  * 
FROM big_vector.nevada
UNION ALL
SELECT  * 
FROM big_vector.newhampshire
UNION ALL
SELECT  * 
FROM big_vector.newjersey
UNION ALL
SELECT  * 
FROM big_vector.newmexico
UNION ALL
SELECT  * 
FROM big_vector.newyork
UNION ALL
SELECT  * 
FROM big_vector.northcarolina
UNION ALL
SELECT  * 
FROM big_vector.northdakota
UNION ALL
SELECT  * 
FROM big_vector.ohio
UNION ALL
SELECT  * 
FROM big_vector.oklahoma
UNION ALL
SELECT  * 
FROM big_vector.oregon
UNION ALL
SELECT  * 
FROM big_vector.pennsylvania
UNION ALL
SELECT  * 
FROM big_vector.rhodeisland
UNION ALL
SELECT  * 
FROM big_vector.southcarolina
UNION ALL
SELECT  * 
FROM big_vector.southdakota
UNION ALL
SELECT  * 
FROM big_vector.tennessee
UNION ALL
SELECT  * 
FROM big_vector.texas
UNION ALL
SELECT  * 
FROM big_vector.utah
UNION ALL
SELECT  * 
FROM big_vector.vermont
UNION ALL
SELECT  * 
FROM big_vector.virginia
UNION ALL
SELECT  * 
FROM big_vector.washington
UNION ALL
SELECT  * 
FROM big_vector.westvirginia
UNION ALL
SELECT  * 
FROM big_vector.wisconsin
UNION ALL
SELECT  * 
FROM big_vector.wyoming

